// This file is @generated by prost-build.
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OffsetSize {
    #[prost(uint32, required, tag = "1")]
    pub offset: u32,
    #[prost(uint32, required, tag = "2")]
    pub size: u32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SegmentSchema {
    #[prost(message, repeated, tag = "1")]
    pub columns: ::prost::alloc::vec::Vec<SegmentColumnSchema>,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SegmentColumnSchema {
    #[prost(uint32, required, tag = "1")]
    pub index: u32,
    #[prost(enumeration = "DType", required, tag = "2")]
    pub dtype: i32,
    #[prost(string, required, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(uint32, required, tag = "4")]
    pub offset: u32,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SegmentFooter {
    #[prost(uint32, required, tag = "1")]
    pub version: u32,
    #[prost(uint32, required, tag = "2")]
    pub name: u32,
    #[prost(message, required, tag = "3")]
    pub schema: SegmentSchema,
    #[prost(message, required, tag = "4")]
    pub keys: OffsetSize,
    #[prost(message, required, tag = "5")]
    pub rows: OffsetSize,
}
#[derive(serde::Serialize, serde::Deserialize)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DType {
    Utf8 = 0,
    I32 = 1,
    F32 = 2,
}
impl DType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Utf8 => "Utf8",
            Self::I32 => "i32",
            Self::F32 => "f32",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Utf8" => Some(Self::Utf8),
            "i32" => Some(Self::I32),
            "f32" => Some(Self::F32),
            _ => None,
        }
    }
}
